### ISSUE TITLE
Generated EPW file has blank lines between each record on windows

### ISSUE THREAD

**Issue by samuelduchesne** [IMMM-SFA/diyepw#61]
Hi there! I am using the package on windows and blank lines  are created between each records of the resulting EPW file.

**Comment by thurber** [comment]
thanks for reporting @samuelduchesne, and apologies for the delay -- i've just released v1.2.2 which tries to address this issue; can you check if it works for you?

**Comment by samuelduchesne** [comment]
I'm quite busy currently. I'll try to have look in the coming days

**Comment by samuelduchesne** [comment]
Hi @thurber! I was using the tool again today and hit that issue again. #64 should fix it. I haven't tested on Linux on MacOs. Can you give it a try?

**Comment by BenjaminStuermer** [comment]
@thurber Original author here! (I still get notifications when stuff happens on this repo.) What happens if you restore the `newline=''` argument passed to open()? I was wondering when I saw that whether that might cause issues in non-Windows systems. Otherwise, what error are you getting? I obviously don't have DIYEPW set up to run on my system any longer, but maybe I'd have an idea what's going on.

**Comment by thurber** [comment]
thanks @BenjaminStuermer; the resulting files on mac/nix have no line separator between the header row and the value row. Adding one more linesep passes the tests: 
```python
        with open(save_path, 'w', newline='') as epw_file:
            epw_file.writelines([
                location_header,
                os.linesep,
                os.linesep.join(self._headers[1:5]),
                self._comment,

                'COMMENTS 2, TMY3 data from energyplus.net/weather supplemented with NOAA ISD Lite data from ' +
                'https://www1.ncdc.noaa.gov/pub/data/noaa/isd-lite/ for an actual meteorological year (AMY)',

                'DATA PERIODS,1,1,Data,' + first_day_of_week + ', 1/1, 12/31'
            ])
            self._observations.to_csv(epw_file, header=False, index=False)
```

**Comment by thurber** [comment]
@samuelduchesne, would you be able to check if the version above still works for you on Windows? If not, I can branch the logic based on OS.

**Comment by samuelduchesne** [comment]
See #65

**Comment by thurber** [comment]
Thanks @samuelduchesne! I'll releaae an updated version to PyPi later today!
